-- Données de démonstration fictives, jamais présentées comme un agenda vérifié.
INSERT INTO idee_category (slug,name,icon) VALUES ('nature','Nature & balades','trees'),('culture','Culture & patrimoine','building-bank'),('marche','Marchés & terroir','basket'),('famille','En famille','users'),('spectacle','Concerts & spectacles','music'),('atelier','Ateliers & rencontres','palette');
INSERT INTO idee_place (name,city,department) VALUES ('Centre-ville','Strasbourg','67'),('Vieille ville','Colmar','68'),('Piémont des Vosges','Obernai','67'),('Centre culturel','Mulhouse','68'),('Vignoble','Eguisheim','68'),('Parc urbain','Sélestat','67');
INSERT INTO idee_outing (slug,title,summary,description,kind,status,place_id,environment,min_age,duration_minutes,is_demo,practical_info) VALUES
('balade-vignoble','Une balade au fil des vignes','Prendre les chemins du vignoble et profiter des paysages alsaciens.','Une idée de promenade entre villages et coteaux. Cet exemple illustre une sortie permanente, à organiser selon la météo et les conditions locales.','permanent','published',5,'outdoor',0,120,true,'Prévoir des chaussures de marche et de l’eau. Itinéraire à confirmer.'),
('marche-createurs','Le rendez-vous des créateurs','Flâner entre les stands et découvrir des créations artisanales.','Un marché fictif pour illustrer une récurrence : le premier samedi de chaque mois, de 10 h à 18 h.','event','published',1,'outdoor',0,null,true,'Exemple de calendrier mensuel ; aucun événement réel annoncé.'),
('weekend-patrimoine','Un week-end de découvertes','Trois jours pour explorer le patrimoine et les savoir-faire.','Un événement fictif réparti sur trois jours. Chaque journée possède ses horaires ; il n’est pas présenté comme ouvert pendant la nuit.','event','published',2,'mixed',0,null,true,'Programme de démonstration.'),
('atelier-famille','Un atelier à partager en famille','Créer, essayer et repartir avec une idée pleine de couleurs.','Un atelier fictif proposé le mercredi et le samedi après-midi. Cet exemple utilise une règle hebdomadaire et un tarif par participant.','event','published',4,'indoor',6,90,true,'Exemple uniquement : aucune réservation disponible.'),
('escapade-vosges','Une échappée au pied des Vosges','S’offrir une pause au vert sur les sentiers du piémont.','Une idée de sortie nature sans date imposée. Les conditions d’accès, l’itinéraire et la météo doivent être vérifiés avant de partir.','permanent','published',3,'outdoor',8,180,true,'Équipement adapté au terrain conseillé.'),
('concert-soiree','Une soirée en musique','Un moment musical pour prolonger la journée.','Un concert fictif en soirée pour illustrer un événement ponctuel avec heure de début et heure de fin.','event','published',6,'outdoor',0,120,true,'Date et programme fictifs.');
INSERT INTO idee_outing_category VALUES (1,1),(1,4),(2,3),(2,6),(3,2),(3,4),(4,4),(4,6),(5,1),(6,5);
INSERT INTO idee_price (outing_id,label,amount,price_type) VALUES (1,'Accès libre',0,'free'),(2,'Entrée',0,'free'),(3,'Entrée',0,'free'),(4,'Par participant',12,'fixed'),(5,'Accès libre',0,'free'),(6,'Entrée',null,'unknown');
INSERT INTO idee_schedule (outing_id,label,starts_local,ends_local,rrule) VALUES
(2,'Tous les premiers samedis du mois','2026-01-03 10:00','2026-01-03 18:00','FREQ=MONTHLY;BYDAY=1SA'),
(3,'Trois jours, de 10 h à 18 h', (current_date + (5-extract(isodow from current_date)::int+7)%7) + time '10:00', (current_date + (5-extract(isodow from current_date)::int+7)%7) + time '18:00','FREQ=DAILY;COUNT=3'),
(4,'Les mercredis et samedis, à 14 h',current_date + time '14:00',current_date + time '15:30','FREQ=WEEKLY;BYDAY=WE,SA'),
(6,'Une soirée, de 20 h à 22 h',current_date + 3 + time '20:00',current_date + 3 + time '22:00',null);
